### ISSUE TITLE
Stickem ignores container until page is resized

### ISSUE THREAD

**Issue by ghost** [davist11/jQuery-Stickem#19]
I'm not sure why, but on refresh the .stickem element will either scroll up or down past the container. When the page is resized (either with a developer tools window or just by dragging a corner) the .stickem element jumps to its correct position. I've included a link in case this doesn't make sense.

http://client.analog.la/ret5/artists/tomorrow-we-move-to-hawaii/

**Comment by jacobraccuia** [comment]
man I'm havin this problem now..... ugh
