### ISSUE TITLE
Dynamic Content

### ISSUE THREAD

**Issue by taskianna** [davist11/jQuery-Stickem#31]
Hello, I'm working on a page with dynamic items, the user has the option to remove/filter some items, I'm calling destroy and initialize after postback but if the page is scrolled for example in the middle, the stickem would still work but the sticky item is a bit messed up. How do I initialize it again even if the page scrollTop is not zero? Thanks

**Comment by joker-777** [comment]
It would be nice if there would be the possibility to listen to the size of the container element and reset stickem when changing. Do you guys now any possible solution for this?

**Comment by Spir** [comment]
Since position: sticky is pretty available now (http://caniuse.com/#feat=css-sticky) I have switch to using a polyfill when not available:
https://github.com/wilddeer/stickyfill

I'm pretty happy with it.

**Comment by davist11** [comment]
Yup exactly. `position: sticky` is really a better method these days.

**Comment by joker-777** [comment]
But it looks like it isn't supported by IE at all. This isn't  really an option, therefore.

**Comment by davist11** [comment]
There are many polyfills available

**Comment by Spir** [comment]
The polyfill is supporting IE9+. Use "position: sticky" add the polyfill and this JS code:

```
var stickyElements = document.getElementsByClassName('sticky');

for (var i = stickyElements.length - 1; i >= 0; i--) {
    Stickyfill.add(stickyElements[i]);
}
```

And you are done!
