### ISSUE TITLE
Source Missing License Header 

### ISSUE THREAD

**Issue by KelseyBlodgett** [davist11/jQuery-Stickem#43]
I noticed that the JavaScript file doesn't have a license header. This seems to be a common practice amongst JavaScript libraries.
Would it be possible to add the information to the file so users can easily adhere to the project's license?
Something like:
Licensed under the MIT License
Thanks.

**Comment by davist11** [comment]
Added a license file to the repo: https://github.com/davist11/jQuery-Stickem/blob/master/LICENSE.md

**Comment by KelseyBlodgett** [comment]
thanks!
