### ISSUE TITLE
Sticky text disappearing when next container title gets class "stickit" with masonry.js

### ISSUE THREAD

**Issue by garretthaas** [davist11/jQuery-Stickem#46]
Thanks for making this plugin. It has been great so far. Wondering your thoughts on this.

I'm using masonry.js with Stickem. The text in the titles that are sticking disappear when the next container title gets the class "stickit". See this fiddle for an example... http://jsfiddle.net/sjpLv3of/6/ 

When I'm not using masonry.js it works as expected. Any ideas?

**Comment by javiercejudo** [comment]
It looks like the titles on the left hand side are simply on top of the ones on the right, because your `.sticky` has 100% width. Changed the width to 30% and it looks ok: http://jsfiddle.net/sjpLv3of/8/

I don't think this is a jQuery-Stickem issue.

**Comment by garretthaas** [comment]
Agreed. this is not a jQuery-Stickem issue. It was a css issue.
