### ISSUE TITLE
Allow for sticking at the bottom too.

### ISSUE THREAD

**Issue by zoffixznet** [davist11/jQuery-Stickem#47]
Would be nice to have the option to stick at the `top`, `top+bottom`, and `bottom`.

This way, for example, if `top+bottom` is set, the element would always be on the screen, sticking to the top or bottom of the window whenever needed.

`top` would be the current behaviour, and `bottom` would be what the current behaviour would look like if you turned the monitor upside down.

**Comment by davist11** [comment]
So the use case is if you turn your monitor upside down?

**Comment by zoffixznet** [comment]
Hey,

I actually ended up using another framework to find a solution (Waypoints)... it also didn't have the option, but I did make an example of what I'm talking about using that framework. You can view it here: http://zoffix.com/new/del/WayPoints-Issue-Sample/WayPoint-Sample.html

The red bar is a sticky that's initially stuck to the bottom of the window, but it gets unstuck once you reach the footer (the black region)
