### ISSUE TITLE
Not working with viewportUnits

### ISSUE THREAD

**Issue by renatodeleao** [davist11/jQuery-Stickem#48]
First: awesome work man.

Second: i'm using it on a sticky sidebar, if `height` is defined in pixels or not defined at all, works like charm. If viewport units are used, the plugin doesn't init. I've looked at your code, (although my js skills aren't that great) and can't spot anything wrong since `elemHeight: $this.height()` should get the value even if defined in `vh`. No error is thrown to the console either.

Any thoughts?

_Edit: retested and works if `height < 90vh`, which is kinda of weird and this is an aprox value_

See for yourself: http://codepen.io/ohsimtabem/pen/MYzEKN

**Comment by javiercejudo** [comment]
I think that your setup is somehow not satisfying this condition (https://github.com/davist11/jQuery-Stickem/blob/5959084479c4d3ea1434812fb0182bc0c00002fe/jquery.stickem.js#L77) and hence your element (item) is never added to the array of items.

This works for me with height up to 99vh http://codepen.io/javiercejudo/pen/gbQoRm (I made `overflow-x: hidden` in the body to avoid the horizontal scroll).

PS: there is a PR (https://github.com/davist11/jQuery-Stickem/pull/13/files) to configure how to handle the case in which the container is higher than the window

**Comment by renatodeleao** [comment]
@javiercejudo well spotted!

That makes sense, and overflow-x:hidden makes it possible to go up to the `99.9vh` which will do the trick. 
But somehow on my client's project i can't pass the `94vh` which is odd, have to check what am i doing wrong, but it's probably due a top sticky nav that i've already fixed and the offset that i need. 

Thanks for the enlightenment!

**Comment by javiercejudo** [comment]
No worries. Don't forget to close the issue if you are convinced it isn't a jQuery-Stickem bug.
