### ISSUE TITLE
How to make jQuery-Stickem with body {overflow: hidden} ?

### ISSUE THREAD

**Issue by Xavours** [davist11/jQuery-Stickem#50]
Hey !

First, thank you, for this great tool, it is really enjoyable. I am coding a website where i am trying to use it in a div is scrollable, while the body element is not and has to stay like that. I noticed that in that condition the plug in does not work while it's perfectly working if the body is set on overflow: auto or scroll. Is there any way that could make it works in those conditions too ?

Thank you !

**Comment by davist11** [comment]
As of right now, you cannot use it like that.
