### ISSUE TITLE
bower? npm?

### ISSUE THREAD

**Issue by rdpascua** [davist11/jQuery-Stickem#53]
Do you have any plans for this?

**Comment by smilledge** [comment]
Looks like it's available on Bower as `stickem`. But it's using the deprecated `component.json` so I might not work in the future...

**Comment by buck3000** [comment]
https://yarnpkg.com/en/package/jquery-stickem

**Comment by buck3000** [comment]
I just forked it and threw it up - was attempting to be helpful, obviously happy to take it down or do whatever the maintainers intend here.

**Comment by davist11** [comment]
I really wouldn't recommend using this anymore. `position: sticky` plus a polyfill is a <a href="http://caniuse.com/#feat=css-sticky">much better approach</a>.
