### ISSUE TITLE
sticky inside bootstrap tabs not working

### ISSUE THREAD

**Issue by chandru1822** [davist11/jQuery-Stickem#59]
I want to use sticky inside bootstrap tabs.But the sticky is working only in the first active tab. please guide me how to use stickem inside bootstrap tabs.

**Comment by davist11** [comment]
At this point, I would recommend using `position: sticky` with a polyfill. http://caniuse.com/#search=sticky

**Comment by chandru1822** [comment]
position: sticky will not work in some of the browser. So, can u please give me some other suggestions.
Are u referring me this link https://philipwalton.github.io/polyfill/demos/position-sticky/ ??
Also, position: sticky with polyfill is used only for demonstartion purpose and still not used for production code,because currently there is no w3c specification for this.

**Comment by davist11** [comment]
Yup, that's what the polyfill is for, to support those other browsers.

**Comment by chandru1822** [comment]
Sorry. Its not working properly in all versions of IE and Edge.
