### ISSUE TITLE
where to add the files and jquery line

### ISSUE THREAD

**Issue by adri9deu** [davist11/jQuery-Stickem#60]
Hi,

2 questions:

1- I added the folder directly into my server root, is it ok? Or I should add the files into a specific folder?
2- I added the jquery code lines `$('.container').stickem();` in the `<body>` of the page, just before than `<div>` I like to enable the stickem. Is it ok?

Thanks

**Comment by davist11** [comment]
1. That's kind of up to you how you want to organize things
1. That's not necessarily the best place to put it, but again, you can organize things a million different ways. The ideal place to put your JavaScript would be in a separate JavaScript file or before the `</body>` tag.

**Comment by adri9deu** [comment]
Hi Davist,

Thanks for your help.

The problem is that it does not work, it is why I am asking that.
I have checked and all the code I added is correct.

So, any idea?

I will try to figure out the problem anyway

**Comment by davist11** [comment]
Without a link, I can't really help.

**Comment by adri9deu** [comment]
here you go: [here](https://www.finzauto.com/car/bmw-serie-1-2008-3/)

the `<div>` what I which I call `$('.holaa').stickem();` is `.holaa`, and the `<div>` where I want to apply the stickem is `#extra-contacto` 

thanks

**Comment by davist11** [comment]
You have JavaScript errors that you will need to fix

**Comment by adri9deu** [comment]
ok, fixed! The root of js was wrong.

Now one more thing: when scroll finishes, the item returns to original position, but I would like that the item keeps at the bottom of its <div>, just same as your example.

Do you know what I mean?

**Comment by davist11** [comment]
Sounds like you are probably missing CSS that styles it when it's reached it's end position.

**Comment by adri9deu** [comment]
Ok I will try to add some css styles, keep you posted
