### ISSUE TITLE
where to change start: 0

### ISSUE THREAD

**Issue by adri9deu** [davist11/jQuery-Stickem#61]
Hi,

how can I change when the items should start to be sticky?

in your code, is here:

```
Stickem.prototype = {
		defaults: {
			item: '.stickem',
			container: '.stickem-container',
			stickClass: 'stickit',
			endStickClass: 'stickit-end',
			offset: 0,
			start: 0,
			onStick: null,
			onUnstick: null
		},
```
but I need to set a different start for different items.

Thanks

**Comment by davist11** [comment]
At this point, I think the best option would be to use `position: sticky` with a polyfill instead. This plugin is quite old, and `position: sticky` is much simpler to work with: https://caniuse.com/#search=sticky

**Comment by adri9deu** [comment]
Hi! I am trying to use `position: sticky` attribute but it does not work on my page. I searched in some forums but no solution found.

The only thing I need for full working is to set a different start for 2 items in the same page. Any idea?

Thanks

**Comment by davist11** [comment]
You should read the documentation on <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/position#sticky">position: sticky</a>
